version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: laonedb
      POSTGRES_USER: laoneuser
      POSTGRES_PASSWORD: laonepassword
    ports:
      - "5432:5432"
    networks:
      - dem

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: alexandr.kosyrew@mail.ru
  #     PGADMIN_DEFAULT_PASSWORD: laonepassword
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - dem

  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - rabbit
    networks:
      - dem

  celery-worker:
    build: .
    container_name: celery-worker
    command: celery -A celery_app worker -l info --concurrency=1 -P solo
    restart: always
    depends_on:
      - rabbit
      - postgres
    networks:
      - dem
    links:
      - rabbit

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A celery_app beat -l info
    restart: always
    depends_on:
      - rabbit
      - postgres
    networks:
      - dem
    links:
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    hostname: rabbit
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=admin
    #   - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "5682:5672"
      - "15682:15672"
    networks:
      - dem

  celery-flower:
    build: .
    container_name: celery-flower
    command: celery -A celery_app flower
    restart: always
    ports:
      - "5555:5555"
    depends_on:
      - rabbit
      - postgres
    networks:
      - dem

networks:
  dem: