version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: laonedb
      POSTGRES_USER: laoneuser
      POSTGRES_PASSWORD: laonepassword
    ports:
      - "5432:5432"
    networks:
      - dem

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: alexandr.kosyrew@mail.ru
      PGADMIN_DEFAULT_PASSWORD: laonepassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5000:80"
    depends_on:
      - postgres
    networks:
      - dem

  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - dem

  celery:
    build: .
    command:
      - celery -A celery_app beat -l info
      - celery -A celery_config worker -l info --concurrency=1 -P solo
    depends_on:
      - app
    networks:
      - dem

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - dem
    depends_on:
      - app

  flower:
    build: .
    command: celery -A celery_app flower
    ports:
      - "5555:5555"
    depends_on:
      - app
      - celery

networks:
  dem: